# Generated by Django 6.0.3 on 2026-04-13 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('ODS_port', 'Odesa Port'), ('ILK_port', 'Chornomorsk Port'), ('YUZ_port', 'Pivdenne Port'), ('AZ_depot', 'A-Z Terminals Depot'), ('Liski_depot', 'Liski Depot'), ('Gefest_depot', 'Gefest Depot'), ('Nika_Marine_depot', 'Nika Marine Depot')], max_length=20)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=20, unique=True)),
                ('shipper', models.CharField(max_length=150)),
                ('consignee', models.CharField(max_length=150)),
                ('notify_party', models.CharField(max_length=150)),
                ('vessel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('voyage', models.CharField(blank=True, max_length=10, null=True)),
                ('pol', models.CharField(max_length=100, verbose_name='Port of Loading')),
                ('pod', models.CharField(max_length=100, verbose_name='Port of Discharge')),
                ('etd', models.DateField(blank=True, null=True)),
                ('eta', models.DateField(blank=True, null=True)),
                ('free_time_until', models.DateField(blank=True, null=True)),
                ('cargo_description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('forwarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=15, unique=True)),
                ('container_type', models.CharField(choices=[('20DV', '20DV'), ('40DV', '40DV'), ('40HC', '40HC'), ('40HR', '40HR')], max_length=10)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('issued', 'Issued'), ('picked_up', 'Picked Up'), ('loaded', 'Loaded Full'), ('in_transit', 'In Transit'), ('delivered', 'Delivered Full'), ('empty_returned', 'Empty Returned')], default='planned', max_length=20)),
                ('cargo_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tare_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='logistics_app.booking')),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='logistics_app.location')),
            ],
        ),
    ]
