# Generated by Django 6.0.3 on 2026-04-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_type',
        ),
    ]
