# Generated by Django 6.0.3 on 2026-04-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0002_remove_location_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='payload',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
